package xyz.devcmb.cmr.minigames;

public enum MinigameFlag {
    DISABLE_FALL_DAMAGE,
    PVP_DISABLED,
    UNLIMITED_BLOCKS,
    CANNOT_BREAK_BLOCKS,
    CANNOT_PLACE_BLOCKS,
    DISABLE_OFF_HAND,
    DISABLE_BLOCK_DROPS,
    DISABLE_PLAYER_DEATH_DROP,
    DISPLAY_KILLER_IN_DEATH_MESSAGE,
    DO_NOT_CONSUME_FIREWORKS,
    NO_REPEATED_TOOLS,
    CANNOT_TRAMPLE_FARMLAND
}
