maps:
  Capture the Flag:
    - map:
        # This is where you fill out all the information about the map for the Capture the Flag minigame.
        worldName: ""
        voidHeight: 0
        redTeamSpawn:
          x: 0
          y: 0
          z: 0
          pitch: 0
          yaw: 90
        blueTeamSpawn:
          x: 0
          y: 0
          z: 0
          pitch: 0
          yaw: -90
        flags:
          redFlag:
            x: 0
            y: 0
            z: 0
          blueFlag:
            x: 0
            y: 0
            z: 0
          redFlagClaim:
            from:
              x: 0
              y: 0
              z: 0
            to:
              x: 0
              y: 0
              z: 0
          blueFlagClaim:
            from:
              x: 0
              y: 0
              z: 0
            to:
              x: 0
              y: 0
              z: 0
        itemSpawnLocations:
          - location:
              x: 0
              y: 0
              z: 0
  Kaboomers:
    - map:
        worldName: ""
        voidHeight: 0
        redTeamSpawn:
          x: 0
          y: 0
          z: 0
        blueTeamSpawn:
          x: 0
          y: 0
          z: 0
  Brawl:
    - map:
        worldName: ""
        voidHeight:
        spawn:
          x: 0
          y: 0
          z: 0
        chests:
          large:
            - location:
                x: 0
                y: 0
                z: 0
          small:
            - location:
                x: 0
                y: 0
                z: 0
  Sniffer Caretaker:
    - map:
        worldName: ""
        voidHeight: 0
        redTeamSpawn:
          x: 0
          y: 0
          z: 0
        blueTeamSpawn:
          x: 0
          y: 0
          z: 0
        redTeamBarrier:
          from:
            x: 0
            y: 0
            z: 0
          to:
            x: 0
            y: 0
            z: 0
        blueTeamBarrier:
          from:
            x: 0
            y: 0
            z: 0
          to:
            x: 0
            y: 0
            z: 0
        redTeamSnifferSpawn:
          x: 0
          y: 0
          z: 0
        blueTeamSnifferSpawn:
          x: 0
          y: 0
          z: 0
        eventSpawnLocations:
          from:
            x: 0
            y: 0
            z: 0
          to:
            x: 0
            y: 0
            z: 0
        redBasePreventPlace:
          from:
            x: 0
            y: 0
            z: 0
          to:
            x: 0
            y: 0
            z: 0
        blueBasePreventPlace:
          from:
            x: 0
            y: 0
            z: 0
          to:
            x: 0
            y: 0
            z: 0
        redSnifferZone:
          from:
            x: 0
            y: 0
            z: 0
          to:
            x: 0
            y: 0
            z: 0
        blueSnifferZone:
          from:
            x: 0
            y: 0
            z: 0
          to:
            x: 0
            y: 0
            z: 0
  Cooking Chaos:
    - map:
        worldName: ""
        voidHeight: 0
        redSpawn:
            x: 0
            y: 0
            z: 0
        blueSpawn:
            x: 0
            y: 0
            z: 0
        redBarrier:
            from:
                x: 0
                y: 0
                z: 0
            to:
                x: 0
                y: 0
                z: 0
        blueBarrier:
            from:
                x: 0
                y: 0
                z: 0
            to:
                x: 0
                y: 0
                z: 0
        boneMealChests:
          - location:
              x: 0
              y: 0
              z: 0
        redEntrance:
            x: 0
            y: 0
            z: 0
        redTables:
          - seats:
              - location:
                  x: 0
                  y: 0
                  z: 0
                  yaw: 0
                  pitch: 0
        blueEntrance:
            x: 0
            y: 0
            z: 0
        blueTables:
            - seats:
                - location:
                    x: 0
                    y: 0
                    z: 0
                    yaw: 0
                    pitch: 0
  Electric Eel:
    - map:
        worldName: ""
        voidHeight: 0
        redSpawn:
            x: 0
            y: 0
            z: 0
            pitch: 0
            yaw: 0
        blueSpawn:
            x: 0
            y: 0
            z: 0
            pitch: 0
            yaw: 0
        electricEelSpawn:
            x: 0
            y: 0
            z: 0
            pitch: 0
            yaw: 0
        redStorage:
          from:
            x: 0
            y: 0
            z: 0
          to:
            x: 0
            y: 0
            z: 0
        blueStorage:
            from:
                x: 0
                y: 0
                z: 0
            to:
                x: 0
                y: 0
                z: 0
        pollutorBeam:
          x: 0
          y: 0
          z: 0

database:
  host: ""
  port: 3306
  username: ""
  password: ""
  database: ""

settings:
  devMode: false