maps:
  Capture the Flag:
    - map:
        # This is where you fill out all the information about the map for the Capture the Flag minigame.
        worldName: ""
        voidHeight: 0
        redTeamSpawn:
          x: 0
          y: 0
          z: 0
        blueTeamSpawn:
          x: 0
          y: 0
          z: 0
        flags:
          redFlag:
            x: 0
            y: 0
            z: 0
          blueFlag:
            x: 0
            y: 0
            z: 0
          redFlagClaim:
            from:
              x: 0
              y: 0
              z: 0
            to:
              x: 0
              y: 0
              z: 0
          blueFlagClaim:
            from:
              x: 0
              y: 0
              z: 0
            to:
              x: 0
              y: 0
              z: 0